[package]
name = "mprober"
version = "0.6.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
scanner-rust = "1.2"
clap = "2"
byte-unit = "2.1"
serde_json = "1"
termcolor = "1"
terminal_size = "0.1"
getch = "0.2"

libc = "0.2"

[dependencies.validators]
version = "0.20"
features = ["serdely", "rocketly"]