[package]
name = "mprober"
version = "0.6.2"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
scanner-rust = "1.2"
clap = "2"
byte-unit = "2.1"
serde_json = "1"
termcolor = "1"
terminal_size = "0.1"
getch = "0.2"

libc = "0.2"

rand = "0.6"
base64 = "0.10"
enum-ordinalize = "2"
lazy_static = "1"

rocket = "0.4"
rocket-simple-authorization = "0.2"
rocket-cache-response = "0.5"
rocket-json-response = "0.3"

[dependencies.validators]
version = "0.20"
features = ["rocketly"]